# Generated by Django 3.0.2 on 2020-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200121_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
